import Foundation

/// Manages app-level language preference and provides localized string lookup.
///
/// Views that read ``t(_:)`` or ``t(_:_:)`` will re-render when ``language``
/// changes because `bundle` is an `@Observable` tracked property.
@Observable
final class LanguageManager: @unchecked Sendable {
    static let shared = LanguageManager()

    // MARK: - Language enum

    enum AppLanguage: String, CaseIterable, Identifiable, Codable {
        case system
        case en
        case zhHans = "zh-Hans"
        case zhHant = "zh-Hant"

        var id: String { rawValue }

        /// Resolve to a concrete language code (not "system").
        var resolvedCode: String {
            switch self {
            case .system:
                let preferred = Locale.preferredLanguages.first ?? "en"
                if preferred.hasPrefix("zh-Hant") || preferred.hasPrefix("zh-TW") || preferred.hasPrefix("zh-HK") || preferred.hasPrefix("zh-MO") {
                    return "zh-Hant"
                }
                if preferred.hasPrefix("zh") { return "zh-Hans" }
                return "en"
            case .en:
                return "en"
            case .zhHans:
                return "zh-Hans"
            case .zhHant:
                return "zh-Hant"
            }
        }
    }

    // MARK: - State

    var language: AppLanguage {
        didSet {
            UserDefaults.standard.set(language.rawValue, forKey: Self.defaultsKey)
            reloadBundle()
        }
    }

    private(set) var bundle: Bundle

    // MARK: - Init

    private static let defaultsKey = "appLanguage"

    init() {
        let saved = UserDefaults.standard.string(forKey: Self.defaultsKey) ?? "system"
        let lang = AppLanguage(rawValue: saved) ?? .system
        self.language = lang
        self.bundle = Self.resolveBundle(for: lang)
    }

    // MARK: - Localized string access

    /// Look up a localized string by key.
    func t(_ key: String) -> String {
        bundle.localizedString(forKey: key, value: key, table: nil)
    }

    /// Look up a localized format string and apply arguments.
    func t(_ key: String, _ args: any CVarArg...) -> String {
        let format = bundle.localizedString(forKey: key, value: key, table: nil)
        return String(format: format, arguments: args)
    }

    // MARK: - Private

    private func reloadBundle() {
        bundle = Self.resolveBundle(for: language)
    }

    private static func resolveBundle(for language: AppLanguage) -> Bundle {
        let code = language.resolvedCode

        // Bundle.appResources is auto-generated by SPM when resources are declared.
        // SPM `.process()` may lowercase lproj directory names (e.g. "zh-Hans" → "zh-hans"),
        // and Bundle.path(forResource:ofType:) is case-sensitive, so try both variants.
        for candidate in [code, code.lowercased()] {
            if let path = Bundle.appResources.path(forResource: candidate, ofType: "lproj"),
               let localized = Bundle(path: path) {
                return localized
            }
        }

        // Fallback to English
        for candidate in ["en", "En"] {
            if let path = Bundle.appResources.path(forResource: candidate, ofType: "lproj"),
               let localized = Bundle(path: path) {
                return localized
            }
        }

        return Bundle.appResources
    }
}
